import {
  pgTable,
  serial,
  integer,
  numeric,
  text,
  timestamp,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";

import { productsTable } from "./products";
import { supplierDebtsTable } from "./debts";

/**
 * One stock procurement event.
 *
 * Purchases deliberately stay lightweight.
 * They answer:
 *
 * - When did we buy stock?
 * - Who supplied it?
 * - Roughly what stock came in?
 * - How much did the goods cost?
 * - What additional procurement costs were incurred?
 * - How much was paid?
 * - How much remains owed?
 *
 * Detailed sellable-product information belongs to Inventory.
 */
export const stockPurchasesTable = pgTable(
  "stock_purchases",
  {
    id: serial("id").primaryKey(),

    /**
     * Human-friendly permanent identifier.
     *
     * Example:
     * PUR-2026-0001
     *
     * Generated by the backend — never typed by the owner.
     */
    purchaseNumber: text("purchase_number"),

    supplierName: text("supplier_name").notNull(),

    /**
     * Optional because we do not want to force repetitive data entry.
     * Later, known suppliers can provide this automatically.
     */
    supplierPhone: text("supplier_phone"),

    /**
     * Business date of the procurement.
     *
     * Kept separately from createdAt because the owner may record
     * yesterday's purchase today.
     */
    purchaseDate: timestamp("purchase_date", {
      withTimezone: true,
    })
      .notNull()
      .defaultNow(),

    /**
     * Total amount paid / payable for the STOCK itself,
     * before transport, packaging and other direct procurement costs.
     *
     * Under the new purchase model this is entered once for the
     * entire procurement rather than calculated product-by-product.
     */
    goodsTotal: numeric("goods_total", {
      precision: 12,
      scale: 2,
    })
      .notNull()
      .default("0"),

    /**
     * Sum of flexible additional procurement costs.
     *
     * Calculated by the backend from stock_purchase_costs.
     */
    sharedCostsTotal: numeric("shared_costs_total", {
      precision: 12,
      scale: 2,
    })
      .notNull()
      .default("0"),

    /**
     * goodsTotal + sharedCostsTotal
     */
    totalCost: numeric("total_cost", {
      precision: 12,
      scale: 2,
    })
      .notNull()
      .default("0"),

    /**
     * Cash actually paid toward this procurement.
     *
     * supplier balance = totalCost - amountPaid
     */
    amountPaid: numeric("amount_paid", {
      precision: 12,
      scale: 2,
    })
      .notNull()
      .default("0"),

    /**
     * Supplier debt generated automatically when amountPaid
     * is lower than totalCost.
     */
    supplierDebtId: integer("supplier_debt_id").references(
      () => supplierDebtsTable.id,
      {
        onDelete: "set null",
      },
    ),

    /**
     * Optional supplier invoice / receipt / transaction reference.
     */
    reference: text("reference"),

    notes: text("notes"),

    /**
     * System timestamp: when Tres Bien actually received the record.
     * This is intentionally different from purchaseDate.
     */
    createdAt: timestamp("created_at", {
      withTimezone: true,
    })
      .notNull()
      .defaultNow(),

    updatedAt: timestamp("updated_at", {
      withTimezone: true,
    })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    uniqueIndex("stock_purchases_purchase_number_idx").on(table.purchaseNumber),

    index("stock_purchases_purchase_date_idx").on(table.purchaseDate),

    index("stock_purchases_supplier_debt_id_idx").on(table.supplierDebtId),
  ],
);

/**
 * Lightweight description of stock acquired in a purchase.
 *
 * Example:
 *
 * Handbags -> 20 pieces
 * Shoes    -> 6 pairs
 * Dresses  -> 8 pieces
 *
 * This does NOT create inventory products.
 *
 * Photos, styles, colours, sizes, selling prices and detailed
 * product attributes continue to belong to Inventory.
 */
export const stockPurchaseGroupsTable = pgTable(
  "stock_purchase_groups",
  {
    id: serial("id").primaryKey(),

    purchaseId: integer("purchase_id")
      .notNull()
      .references(() => stockPurchasesTable.id, {
        onDelete: "cascade",
      }),

    category: text("category").notNull(),

    quantity: integer("quantity").notNull(),

    /**
     * Supplier price for one unit in this stock group,
     * before transport and other shared procurement costs.
     *
     * Example:
     * 5 handbags bought at KSh 1,000 each -> 1000.00
     *
     * Shared costs are allocated separately when landed cost
     * is calculated.
     */
    unitBuyingPrice: numeric("unit_buying_price", {
      precision: 12,
      scale: 2,
    })
      .notNull()
      .default("0"),

    /**
     * Optional short description only when useful.
     *
     * Example:
     * "Mixed small shoulder bags"
     *
     * The normal purchase flow should not require this.
     */
    description: text("description"),

    createdAt: timestamp("created_at", {
      withTimezone: true,
    })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("stock_purchase_groups_purchase_id_idx").on(table.purchaseId),

    index("stock_purchase_groups_category_idx").on(table.category),
  ],
);

/**
 * LEGACY PURCHASE ITEMS
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * Older Tres Bien purchases were recorded product-by-product and linked
 * directly to Inventory.
 *
 * We keep this table so existing purchase history is not destroyed when
 * moving to the simpler purchase workflow.
 *
 * New purchases should use stockPurchaseGroupsTable instead.
 */
export const stockPurchaseItemsTable = pgTable(
  "stock_purchase_items",
  {
    id: serial("id").primaryKey(),

    purchaseId: integer("purchase_id")
      .notNull()
      .references(() => stockPurchasesTable.id, {
        onDelete: "cascade",
      }),

    productId: integer("product_id")
      .notNull()
      .references(() => productsTable.id, {
        onDelete: "restrict",
      }),

    quantity: integer("quantity").notNull(),

    unitBuyingPrice: numeric("unit_buying_price", {
      precision: 12,
      scale: 2,
    }).notNull(),

    goodsSubtotal: numeric("goods_subtotal", {
      precision: 12,
      scale: 2,
    }).notNull(),

    allocatedSharedCost: numeric("allocated_shared_cost", {
      precision: 12,
      scale: 2,
    })
      .notNull()
      .default("0"),

    landedSubtotal: numeric("landed_subtotal", {
      precision: 12,
      scale: 2,
    }).notNull(),

    landedUnitCost: numeric("landed_unit_cost", {
      precision: 12,
      scale: 2,
    }).notNull(),

    createdAt: timestamp("created_at", {
      withTimezone: true,
    })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("stock_purchase_items_purchase_id_idx").on(table.purchaseId),

    index("stock_purchase_items_product_id_idx").on(table.productId),
  ],
);

/**
 * Flexible additional procurement costs.
 *
 * Examples:
 * - Transport
 * - Packaging
 * - Loading
 * - Delivery
 * - Agent fee
 * - Other
 *
 * These stay separate so the normal Record Purchase screen can simply
 * show "+ Add cost" rather than a long permanent form.
 */
export const stockPurchaseCostsTable = pgTable(
  "stock_purchase_costs",
  {
    id: serial("id").primaryKey(),

    purchaseId: integer("purchase_id")
      .notNull()
      .references(() => stockPurchasesTable.id, {
        onDelete: "cascade",
      }),

    label: text("label").notNull(),

    amount: numeric("amount", {
      precision: 12,
      scale: 2,
    }).notNull(),

    createdAt: timestamp("created_at", {
      withTimezone: true,
    })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("stock_purchase_costs_purchase_id_idx").on(table.purchaseId),
  ],
);

export type StockPurchase = typeof stockPurchasesTable.$inferSelect;

export type StockPurchaseGroup = typeof stockPurchaseGroupsTable.$inferSelect;

/**
 * Legacy type retained while old product-level purchase records
 * remain readable.
 */
export type StockPurchaseItem = typeof stockPurchaseItemsTable.$inferSelect;

export type StockPurchaseCost = typeof stockPurchaseCostsTable.$inferSelect;
